### ISSUE TITLE
Unable to install on windows 7 - tried python 3.3 and 3.4

### ISSUE THREAD

**Issue by bscp7** [baudren/NoteOrganiser#88]
pip list:

```
$ c:\Python34\Scripts\pip.exe list
noteorganiser (0.3.0)
pip (8.1.0)
pygments (2.1.3)
pypandoc (1.1.3)
PySide (1.2.4)
qtawesome (0.3.0)
qtpy (1.0b1)
setuptools (18.2)
six (1.10.0)
```

error:

```
$ python NoteOrganiser.py                                                                                                      
Traceback (most recent call last):                                                                                             
  File "NoteOrganiser.py", line 16, in <module>                                                                                
    from noteorganiser.popups import SetExternalEditor                                                                         
  File "C:\Users\user1\AppData\Roaming\Python\Python34\site-packages\noteorganiser-0.3.0-py3.4.egg\noteorganiser\popups.py", line 7, in <module>                                                                                                             
    from .widgets import TagCompletion                                                                                         
  File "C:\Users\user1\AppData\Roaming\Python\Python34\site-packages\noteorganiser-0.3.0-py3.4.egg\noteorganiser\widgets.py", line 9, in <module>                                                                                                            
    import qtawesome                                                                                                           
  File "C:\Users\user1\AppData\Roaming\Python\Python34\site-packages\qtawesome-0.3.0-py3.4.egg\qtawesome\__init__.py", line 19, in <module>                                                                                                                  
    from .iconic_font import IconicFont, set_global_defaults                                                                   
  File "C:\Users\user1\AppData\Roaming\Python\Python34\site-packages\qtawesome-0.3.0-py3.4.egg\qtawesome\iconic_font.py", line 17, in <module>                                                                                                               
    from qtpy.QtCore import Qt, QObject, QPoint, QRect, qRound, QByteArray                                                     
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load                                                           
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked                                                  
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked                                                           
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible                                                
  File "C:\Users\user1\AppData\Roaming\Python\Python34\site-packages\qtpy-1.0b1-py3.4.egg\qtpy\__init__.py", line 68, in <module>                                                                                                                            
AssertionError                                                                                                                                        
```

can you add more details  to installation steps?

**Comment by egolus** [comment]
hello @bhaveshscp 
It looks like an issue with a new version of qtpy to me. I'll look into it

ok, I can reproduce it with python 3.4 x86

**Comment by baudren** [comment]
Hello @bhaveshscp, could you try to downgrade your version of `qtpy`? I am running `0.1.2`, and I think this is the only version we ever tested. This might help you make it work for the moment, while we investigate why the new version does not work.
